# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20171023_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followed_user',
            new_name='following_user',
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
